kind: pipeline
name: default

steps:

- name: test
  image: golang
  commands:
  - go run hello.go

- name: build
  image: golang
  commands:
  - go build

- name: ls
  image: alpine
  commands:
  - ls -al
